#!/bin/sh

export SCALE=1.8
export KEY_COLOR=9889FA
export VALUE_COLOR=FFFFFF
export FPS_ONLY=0

SIMPLEOVERLAY_LIBS="/usr/lib/libsimpleoverlay.so"
### Uncomment for multilib support
#SIMPLEOVERLAY_LIBS="$SIMPLEOVERLAY_LIBS /usr/lib32/libsimpleoverlay.so"

exec env LD_PRELOAD="$SIMPLEOVERLAY_LIBS" "$@"
