#!/bin/sh

export SCALE=1.8
export KEY_COLOR=9889FA
export VALUE_COLOR=FFFFFF
export FPS_ONLY=0

if [ $(uname) != "Darwin" ]; then
    SIMPLEOVERLAY_LIBS="/usr/local/lib/libsimpleoverlay.so"
    ### Uncomment for multilib support
    #SIMPLEOVERLAY_LIBS="$SIMPLEOVERLAY_LIBS /usr/lib32/libsimpleoverlay.so"

    exec env LD_PRELOAD="$SIMPLEOVERLAY_LIBS" "$@"
else
    SIMPLEOVERLAY_LIBS="/usr/local/lib/libsimpleoverlay.dylib"
    exec env DYLD_INSERT_LIBRARIES="$SIMPLEOVERLAY_LIBS" "$@"
fi


